# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/
monitor = HDMI-A-1, highres+highrr, auto-right, 1

# noanim isn't necessary but animations with these rules might look bad. use at your own discretion.
windowrule = noanim, class:^(flameshot)$
windowrule = float, class:^(flameshot)$
windowrule = move 0 0, class:^(flameshot)$
windowrule = pin, class:^(flameshot)$
windowrulev2=fullscreenstate,class:(flameshot),title:(flameshot)
windowrule = noinitialfocus, class:^(flameshot)$
# set this to your leftmost monitor id, otherwise you have to move your cursor to the leftmost monitor
# before executing flameshot
#windowrule = monitor 1, class:^(flameshot)$

