--password-store=gnome-libsecret
--ozone-platform-hint=wayland
--gtk-version=4
--ignore-gpu-blocklist
--enable-features=TouchpadOverscrollHistoryNavigation
--enable-wayland-ime

--enable-gpu-rasterization
--enable-zero-copy
--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoEncoder
--enable-blink-features=MiddleClickAutoscroll
# --ignore-gpu-blocklist
